environment:
  nodejs_version: '18'

matrix:
  fast_finish: true

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm ci --ignore-scripts

test_script:
  - npm run build
  - npm run test:ci

build: off
deploy: off
