name: 'Dependencies Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependencies-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependencies Review'
        uses: actions/dependency-review-action@v2
