name: Release Workflow

on:
  # Triggers the workflow after the Test has completed
  workflow_run:
    workflows: ['Test']
    types:
      - completed
    branches:
      - master
      - next
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Release to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
