name: Test

on:
  # Triggers the workflow on push events
  push:
  # Triggers the workflow on pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Format check'
            cmd: 'npm run format:check'
          - name: 'Lint check'
            cmd: 'npm run lint'
          - name: 'Unit tests'
            cmd: 'npm run test:ci'
          - name: 'Build'
            cmd: 'npm run build'
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/package-lock.json
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: ${{ matrix.name }}
        run: ${{ matrix.cmd }}
